# ./docker-compose.yml

version: '3'

services:
  web:
    image: mattrayner/lamp:latest-1604-php7
    container_name: laravel-php7
    volumes:
      - ./app/:/app
    ports:
      - "8001:80"
    # stdin_open: true
    # tty: true
